Iemeredu29 753/make it possible to add/edit/delete categories list report
BabichevDima/Education-project_OData pull request #2
Opened 2022-08-26 09:06 UTC by BabichevDima

2022-08-29 11:47 UTC, robertiqkkk requested changes

2022-08-29 11:47 UTC, robertiqkkk commented on project007/webapp/controller/BaseController.js
>        getResourceBundle: function (sText) {
i18n (sI18nPath, aParams)

my.Text=My Text ({0}) <- aParams is used here

2022-08-29 11:47 UTC, robertiqkkk commented on project007/webapp/controller/ListReport.controller.js
>      "sap/ui/model/json/JSONModel",
switch to nice namespace

2022-08-29 11:47 UTC, robertiqkkk commented on project007/webapp/controller/ListReport.controller.js
> +        var oODataModel = this.getView().getModel("oData");
switch to "" so it will become default

2022-08-29 11:47 UTC, robertiqkkk commented on project007/webapp/controller/ListReport.controller.js
>          this.byId("CategoriesTable").getItems().forEach((elem) => (elem.mProperties.selected = false));
you are not allowed to use that elem.mProperties

use public methods

https://sapui5.hana.ondemand.com/#/api/sap.m.ListBase%23methods/removeSelections

2022-08-29 11:47 UTC, robertiqkkk commented on project007/webapp/controller/ListReport.controller.js
> +        this.byId("CategoriesTable").setMode("None");
use JSON MODEL

2022-08-29 11:47 UTC, robertiqkkk commented on project007/webapp/controller/ListReport.controller.js
> +        var that = this;
you don't need `that`

2022-08-29 11:47 UTC, robertiqkkk commented on project007/webapp/controller/ListReport.controller.js
>        handleValueHelp: function (oEvent) {
openVHDialog

2022-08-29 11:47 UTC, robertiqkkk commented on project007/webapp/controller/ListReport.controller.js
>            MessageBox.warning(this.getResourceBundle("WarningEditMode"));
disable table items navigation when in Edit mode

2022-08-29 11:47 UTC, robertiqkkk commented on project007/webapp/controller/ListReport.controller.js
> +          this.oDialog = sap.ui.xmlfragment(
Fragment.load

2022-08-29 11:47 UTC, robertiqkkk commented on project007/webapp/controller/ListReport.controller.js
> +            MessageBox.error("Error!!!");
Where is i18n?
Find proper text

2022-08-29 11:47 UTC, robertiqkkk commented on project007/webapp/controller/ListReport.controller.js
> +      },
```suggestion
      onDialogCategoryClosePress: function () {
        this._closeCategoryDialog();
      },

      /**
       * Creates element.
       *
       * @param {string} sQuery create type.
       */
      onCreateCategory: function () {
        this.getView().getModel("oData").submitChanges();
        this._closeCategoryDialog();
      },
      
      _closeCategoryDialog() {
          var oODataModel = this.getView().getModel("oData");
          var oCtx        = this.oDialog.getBindingContext();

          oODataModel.deleteCreatedEntry(oCtx);
          this.oDialog.close();
      }
```

2022-08-29 11:47 UTC, robertiqkkk commented on project007/webapp/controller/ListReport.controller.js
> +      onDeleteButton: function () {
onConfirmDeletion

2022-08-29 11:47 UTC, robertiqkkk commented on project007/webapp/controller/ListReport.controller.js
> +          that.getResourceBundle("WarningMessage") + ` Category?`,
switch to i18n fully

2022-08-29 11:47 UTC, robertiqkkk commented on project007/webapp/controller/ListReport.controller.js
> +              if (sAction === "OK") {
MessageBox.Action.OK

2022-08-29 11:47 UTC, robertiqkkk commented on project007/webapp/view/ListReport.view.xml
> +                        <Button id="DeleteButton" type="Reject" icon="sap-icon://delete" text="{i18n>ButtonDelete}" enabled="{stateModel>/StatusButtons}" press="onWarningMessageDialogPress" visible="
CreateButton

2022-08-30 16:51 UTC, koryakovskaya commented
Approved

2022-08-30 17:01 UTC, merged